# WebSocket MCP Proxy Server Configuration

# Proxy server settings
proxy:
  port: 8080
  host: "0.0.0.0"

# MCP servers to host and proxy
servers:
  # Example: Memory MCP server (works without external dependencies)
  - name: "memory"
    command: "npx"
    args: ["@modelcontextprotocol/server-memory"]
    env:
      NODE_ENV: "production"
    description: "In-memory storage server"
    
  # Example: File system MCP server (using /tmp for demo)
  - name: "filesystem"
    command: "npx"
    args: ["@modelcontextprotocol/server-filesystem", "/tmp"]
    env:
      NODE_ENV: "production"
    description: "File system operations server"

# Logging configuration
logging:
  level: "info"
  format: "json"
  
# Security settings
security:
  # Optional: Restrict which clients can connect
  allowedOrigins: []
  # Optional: API key for authentication
  apiKey: null
